### ISSUE TITLE
Publish video through OpenTok SDK

### ISSUE THREAD

**Issue by Abhishek304** [opentok/opentok-web-samples#213] opened 2021-09-24 07:21 UTC
We are getting 1500 error while publishing video. I have attached screen shot for your reference. Earlier, the same feature was working fine.

But, now we are getting this error.
OT.exception :: title: Unable to Publish (1500) msg: ICEWorkflow
Session.publish :: Could not publish in a reasonable amount of time
Could not publish in a reasonable amount of time

We were not facing this issue with Chrome’s earlier version and when checked by downgrading our Chrome’s version that for version below 83 it is working fine. Versions after 83 seems to have some compatibility issue. 

Kindly look into the issue and let us know if you have any solution to this problem.

We used this link to implement our solution - https://tokbox.com/developer/guides/publish-stream/js/

Chrome Version Used – 94
Opentok SDK Used – 2.20.3 Js and 2.20.2 Android

**Comment by v-kpheng** [comment] 2022-09-28 02:38
@Abhishek304, 2.20 is no longer supported.  Also, quite a few versions of Chrome have been published since then as well.  Can you please see if this can be reproduced using the latest version of the SDK?  Thanks!

Closing, since 2.20 is no longer supported.

**Closed by v-kpheng** 2022-09-28 02:38 UTC
